name: "market_intel"
version: "3.0.0"
config-version: 2

profile: "market_intel"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  market_intel:
    staging:
      +materialized: table
      +schema: stg
    dimensions:
      +materialized: table
      +schema: dimensions
    intermediate:
      +materialized: table
      +schema: int
    marts:
      +materialized: table
      +schema: marts
    exports:
      +materialized: table
      +schema: exports
    reports:
      +materialized: table
      +schema: reports

on-run-start:
