name: "dbt"
version: "3.0.0"
config-version: 2

profile: "dbt"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  dbt:
    raw:
      +materialized: table
      +schema: raw
    staging:
      +materialized: table
      +schema: stg
    intermediate:
      +materialized: table
      +schema: int
    marts:
      +materialized: table
      +schema: marts
    reports:
      +materialized: table
      +schema: reports

on-run-start:
