-- CREATE OR REPLACE TABLE reports.dim_date AS
-- WITH RECURSIVE date_spine(date_day, max_date) AS (
--     SELECT
--         DATE '2018-01-01',
--         DATE '2035-12-31'
--
--     UNION ALL
--
--     SELECT
--         CAST(DATEADD(day, 1, date_day) AS DATE),
--         max_date
--     FROM date_spine
--     WHERE date_day < max_date
-- )
--
-- SELECT
--     date_day                                   AS date_key,
--     EXTRACT(YEAR FROM date_day)                AS year,
--     EXTRACT(QUARTER FROM date_day)             AS quarter,
--     EXTRACT(MONTH FROM date_day)               AS month,
--     EXTRACT(DAY FROM date_day)                 AS day,
--     TRIM(TO_CHAR(date_day, 'MONTH'))           AS month_name,
--     TO_CHAR(date_day, 'MON')                   AS month_name_short,
--     TO_CHAR(date_day, 'YYYY-MM')               AS year_month,
--     EXTRACT(WEEK FROM date_day)                AS week_of_year,
--     TO_CHAR(date_day, 'IYYY-"W"IW')            AS iso_year_week,
--     DATE_TRUNC('week', date_day)               AS week_start_date,
--     EXTRACT(DAYOFWEEK FROM date_day)           AS day_of_week,
--     TRIM(TO_CHAR(date_day, 'DAY'))             AS day_name,
--     TO_CHAR(date_day, 'DY')                    AS day_name_short,
--     CASE WHEN EXTRACT(DAYOFWEEK FROM date_day) IN (0, 6) THEN 1 ELSE 0 END
--                                                 AS is_weekend,
--     CASE WHEN date_day = CURRENT_DATE THEN 1 ELSE 0 END
--                                                 AS is_today,
--     DATE_TRUNC('month', date_day)              AS month_start_date,
--     DATE_TRUNC('quarter', date_day)            AS quarter_start_date,
--     DATE_TRUNC('year', date_day)               AS year_start_date
-- FROM date_spine;
